In [333]:
import numpy as np
import pandas as pd
order=pd.read_csv('Orders_201801_201910.csv')

In [353]:
#extract the rows which has order records
df=order[pd.notna(order['VideoAddOrders'])]
df
export_csv = df.to_csv('OrderRecord.csv')

In [371]:
df.shape
df

,CustomerNodeId,MonthKey,VideoAddOrders,InternetAddOrders,PhoneAddOrders,PhoneLinesAdded,VideoRemoveOrders,InternetRemoveOrders,PhoneRemoveOrders,PhoneLinesRemoved,...,DisconnectOrderTypeCount,SalesOrderOrderTypeCount,SeasonalOrderTypeCount,RestartSalesTypeCount,InstallSalesTypeCount,UpgradeSalesTypeCount,Month_Key,year,month,day
20,2540895,20190901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190901,2019,09,01
24,2540897,20180301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180301,2018,03,01
27,2540897,20180601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180601,2018,06,01
48,2540898,20180501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020180501,2018,05,01
51,2540898,20180801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020180801,2018,08,01
53,2540898,20181001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020181001,2018,10,01
55,2540898,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
56,2540898,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190101,2019,01,01
57,2540898,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
58,2540898,20190301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190301,2019,03,01
59,2540898,20190401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190401,2019,04,01
60,2540898,20190501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190501,2019,05,01
61,2540898,20190601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190601,2019,06,01
62,2540898,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190701,2019,07,01
63,2540898,20190801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190801,2019,08,01
64,2540898,20190901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190901,2019,09,01
65,2540898,20191001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020191001,2019,10,01
75,2540899,20181001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181001,2018,10,01
84,2540899,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190701,2019,07,01
95,2540900,20180801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180801,2018,08,01
124,2540901,20190301,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,1.0,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190301,2019,03,01
145,2540903,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
154,2540906,20180101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180101,2018,01,01
160,2540906,20180701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180701,2018,07,01
166,2540906,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190101,2019,01,01
172,2540906,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190701,2019,07,01
183,2540910,20180801,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,2.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020180801,2018,08,01
200,2540911,20180301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180301,2018,03,01
206,2540911,20180901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180901,2018,09,01
208,2540911,20181101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181101,2018,11,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048301,3421425,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048303,3421425,20190401,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,2.0,1.0,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190401,2019,04,01
1048307,3421425,20190801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190801,2019,08,01
1048346,3421429,20181101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181101,2018,11,01
1048348,3421429,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190101,2019,01,01
1048349,3421429,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048363,3421430,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048365,3421430,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048389,3421431,20191001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020191001,2019,10,01
1048395,3421432,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048397,3421432,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048402,3421432,20190701,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190701,2019,07,01
1048411,3421434,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048412,3421434,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190101,2019,01,01
1048418,3421434,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190701,2019,07,01
1048426,3421435,20181101,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181101,2018,11,01
1048427,3421435,20181201,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048451,3421437,20190801,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190801,2019,08,01
1048459,3421438,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048463,3421438,20190401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190401,2019,04,01
1048467,3421438,20190801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190801,2019,08,01
1048469,3421438,20191001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020191001,2019,10,01
1048507,3421441,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048509,3421441,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048512,3421441,20190501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190501,2019,05,01
1048513,3421441,20190601,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,...,1.0,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190601,2019,06,01
1048522,2885958,20180501,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180501,2018,05,01
1048525,2885958,20180801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180801,2018,08,01
1048531,2885958,20190201,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,2.0,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048574,2885967,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190101,2019,01,01

In [412]:
AddOrder=['VideoAddOrders','InternetAddOrders','PhoneAddOrders','PhoneLinesAdded']
ADD=pd.DataFrame(df[AddOrder].sum())
print(ADD.sum())
ADD

0    30577.0
dtype: float64

                         0
VideoAddOrders      4864.0
InternetAddOrders  22450.0
PhoneAddOrders      1624.0
PhoneLinesAdded     1639.0

In [413]:
RemoveOrder=['VideoRemoveOrders','InternetRemoveOrders','PhoneRemoveOrders','PhoneLinesRemoved']
REMOVE=pd.DataFrame(df[RemoveOrder].sum())
print(REMOVE.sum())
REMOVE

0    28723.0
dtype: float64

                            0
VideoRemoveOrders      6712.0
InternetRemoveOrders  17141.0
PhoneRemoveOrders      2425.0
PhoneLinesRemoved      2445.0

In [414]:
NET_increase= ADD.sum()-REMOVE.sum()
NET_increase

0    1854.0
dtype: float64

In [415]:
TypeCount=['ChangeOfServiceOrderTypeCount',
'DisconnectOrderTypeCount',
'SalesOrderOrderTypeCount',
'SeasonalOrderTypeCount',
'RestartSalesTypeCount',
'InstallSalesTypeCount',
'UpgradeSalesTypeCount']

Type_Count_Sum=pd.DataFrame(df[TypeCount].sum())
Type_Count_Sum

                                      0
ChangeOfServiceOrderTypeCount  105096.0
DisconnectOrderTypeCount        60191.0
SalesOrderOrderTypeCount        22034.0
SeasonalOrderTypeCount            441.0
RestartSalesTypeCount           36948.0
InstallSalesTypeCount             597.0
UpgradeSalesTypeCount            7358.0

In [409]:
TypeCount=['ChangeOfServiceOrderTypeCount',
'DisconnectOrderTypeCount',
'SalesOrderOrderTypeCount',
'SeasonalOrderTypeCount',
'RestartSalesTypeCount',
'InstallSalesTypeCount',
'UpgradeSalesTypeCount']

for i in range(len(TypeCount)):
    #group_count=df[[TypeCount[i],'VideoAddOrders','InternetAddOrders','PhoneAddOrders','PhoneLinesAdded']].groupby(TypeCount[i]).sum()
    #print(group_count)
    print(TypeCount[i])
    print('sum=', df[TypeCount[i]].sum())
    print(df[TypeCount[i]].value_counts())
    print("____________________________________________")

ChangeOfServiceOrderTypeCount
sum= 105096.0
1.0     78744
2.0      9955
3.0      1485
4.0       330
5.0        75
6.0        22
7.0        13
8.0         5
10.0        2
9.0         1
Name: ChangeOfServiceOrderTypeCount, dtype: int64
____________________________________________
DisconnectOrderTypeCount
sum= 60191.0
1.0    45696
2.0     7011
3.0      119
4.0       29
Name: DisconnectOrderTypeCount, dtype: int64
____________________________________________
SalesOrderOrderTypeCount
sum= 22034.0
1.0    21984
2.0       25
Name: SalesOrderOrderTypeCount, dtype: int64
____________________________________________
SeasonalOrderTypeCount
sum= 441.0
1.0    405
2.0     15
3.0      2
Name: SeasonalOrderTypeCount, dtype: int64
____________________________________________
RestartSalesTypeCount
sum= 36948.0
1.0    34083
2.0     1391
4.0       14
3.0        9
Name: RestartSalesTypeCount, dtype: int64
____________________________________________
InstallSalesTypeCount
sum= 597.0
1.0    592
3.0      1
2.0      1
Name: InstallSalesTypeCount, dtype: int64
____________________________________________
UpgradeSalesTypeCount
sum= 7358.0
1.0    7335
2.0       9
5.0       1
Name: UpgradeSalesTypeCount, dtype: int64
____________________________________________

In [410]:
df['TotalOrderedMRC'].describe()

count    127220.000000
mean        105.083163
std          88.867652
min         -25.000000
25%          55.500000
50%          90.500000
75%         140.500000
max        1859.000000
Name: TotalOrderedMRC, dtype: float64

In [411]:
df['TotalOrderedMRC'].sum()

13368679.990000002

In [377]:
date_split=pd.to_datetime(df['MonthKey'],format='%Y%m%d')
date_split_df=pd.DataFrame(date_split)
date_split_df

          MonthKey
20      2019-09-01
24      2018-03-01
27      2018-06-01
48      2018-05-01
51      2018-08-01
53      2018-10-01
55      2018-12-01
56      2019-01-01
57      2019-02-01
58      2019-03-01
59      2019-04-01
60      2019-05-01
61      2019-06-01
62      2019-07-01
63      2019-08-01
64      2019-09-01
65      2019-10-01
75      2018-10-01
84      2019-07-01
95      2018-08-01
124     2019-03-01
145     2019-02-01
154     2018-01-01
160     2018-07-01
166     2019-01-01
172     2019-07-01
183     2018-08-01
200     2018-03-01
206     2018-09-01
208     2018-11-01
...            ...
1048301 2019-02-01
1048303 2019-04-01
1048307 2019-08-01
1048346 2018-11-01
1048348 2019-01-01
1048349 2019-02-01
1048363 2018-12-01
1048365 2019-02-01
1048389 2019-10-01
1048395 2018-12-01
1048397 2019-02-01
1048402 2019-07-01
1048411 2018-12-01
1048412 2019-01-01
1048418 2019-07-01
1048426 2018-11-01
1048427 2018-12-01
1048451 2019-08-01
1048459 2018-12-01
1048463 2019-04-01
1048467 2019-08-01
1048469 2019-10-01
1048507 2018-12-01
1048509 2019-02-01
1048512 2019-05-01
1048513 2019-06-01
1048522 2018-05-01
1048525 2018-08-01
1048531 2019-02-01
1048574 2019-01-01

[127220 rows x 1 columns]

In [387]:
date_split_df[['year','month','day']] = date_split_df['MonthKey'].apply(lambda x: pd.Series(x.strftime("%Y-%m-%d").split("-")))
df

,CustomerNodeId,MonthKey,VideoAddOrders,InternetAddOrders,PhoneAddOrders,PhoneLinesAdded,VideoRemoveOrders,InternetRemoveOrders,PhoneRemoveOrders,PhoneLinesRemoved,...,DisconnectOrderTypeCount,SalesOrderOrderTypeCount,SeasonalOrderTypeCount,RestartSalesTypeCount,InstallSalesTypeCount,UpgradeSalesTypeCount,Month_Key,year,month,day
20,2540895,20190901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190901,2019,09,01
24,2540897,20180301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180301,2018,03,01
27,2540897,20180601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180601,2018,06,01
48,2540898,20180501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020180501,2018,05,01
51,2540898,20180801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020180801,2018,08,01
53,2540898,20181001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020181001,2018,10,01
55,2540898,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
56,2540898,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190101,2019,01,01
57,2540898,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
58,2540898,20190301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190301,2019,03,01
59,2540898,20190401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190401,2019,04,01
60,2540898,20190501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190501,2019,05,01
61,2540898,20190601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190601,2019,06,01
62,2540898,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190701,2019,07,01
63,2540898,20190801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190801,2019,08,01
64,2540898,20190901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190901,2019,09,01
65,2540898,20191001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020191001,2019,10,01
75,2540899,20181001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181001,2018,10,01
84,2540899,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190701,2019,07,01
95,2540900,20180801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180801,2018,08,01
124,2540901,20190301,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,1.0,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190301,2019,03,01
145,2540903,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
154,2540906,20180101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180101,2018,01,01
160,2540906,20180701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180701,2018,07,01
166,2540906,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190101,2019,01,01
172,2540906,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190701,2019,07,01
183,2540910,20180801,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,2.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020180801,2018,08,01
200,2540911,20180301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180301,2018,03,01
206,2540911,20180901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180901,2018,09,01
208,2540911,20181101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181101,2018,11,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048301,3421425,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048303,3421425,20190401,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,2.0,1.0,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190401,2019,04,01
1048307,3421425,20190801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190801,2019,08,01
1048346,3421429,20181101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181101,2018,11,01
1048348,3421429,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190101,2019,01,01
1048349,3421429,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048363,3421430,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048365,3421430,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048389,3421431,20191001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020191001,2019,10,01
1048395,3421432,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048397,3421432,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048402,3421432,20190701,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190701,2019,07,01
1048411,3421434,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048412,3421434,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190101,2019,01,01
1048418,3421434,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190701,2019,07,01
1048426,3421435,20181101,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181101,2018,11,01
1048427,3421435,20181201,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048451,3421437,20190801,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190801,2019,08,01
1048459,3421438,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048463,3421438,20190401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190401,2019,04,01
1048467,3421438,20190801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020190801,2019,08,01
1048469,3421438,20191001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,1.0,NaN,NaN,1970-01-01 00:00:00.020191001,2019,10,01
1048507,3421441,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020181201,2018,12,01
1048509,3421441,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048512,3421441,20190501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190501,2019,05,01
1048513,3421441,20190601,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,...,1.0,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190601,2019,06,01
1048522,2885958,20180501,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180501,2018,05,01
1048525,2885958,20180801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020180801,2018,08,01
1048531,2885958,20190201,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,2.0,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190201,2019,02,01
1048574,2885967,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1970-01-01 00:00:00.020190101,2019,01,01

In [434]:
#df=df.drop('day',axis=1)
df

,CustomerNodeId,MonthKey,VideoAddOrders,InternetAddOrders,PhoneAddOrders,PhoneLinesAdded,VideoRemoveOrders,InternetRemoveOrders,PhoneRemoveOrders,PhoneLinesRemoved,...,TotalOneTimeCharge,ChangeOfServiceOrderTypeCount,DisconnectOrderTypeCount,SalesOrderOrderTypeCount,SeasonalOrderTypeCount,RestartSalesTypeCount,InstallSalesTypeCount,UpgradeSalesTypeCount,year,month
20,2540895,20190901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,09
24,2540897,20180301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,03
27,2540897,20180601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,06
48,2540898,20180501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2018,05
51,2540898,20180801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2018,08
53,2540898,20181001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2018,10
55,2540898,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2018,12
56,2540898,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,01
57,2540898,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,02
58,2540898,20190301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,03
59,2540898,20190401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,04
60,2540898,20190501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,05
61,2540898,20190601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,06
62,2540898,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,07
63,2540898,20190801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,08
64,2540898,20190901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,09
65,2540898,20191001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,10
75,2540899,20181001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,10
84,2540899,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,07
95,2540900,20180801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,08
124,2540901,20190301,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,35.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2019,03
145,2540903,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,02
154,2540906,20180101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,01
160,2540906,20180701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,07
166,2540906,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,01
172,2540906,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,07
183,2540910,20180801,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,2.0,NaN,NaN,1.0,NaN,NaN,2018,08
200,2540911,20180301,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,03
206,2540911,20180901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,09
208,2540911,20181101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048301,3421425,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,02
1048303,3421425,20190401,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,90.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN,2019,04
1048307,3421425,20190801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,08
1048346,3421429,20181101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,11
1048348,3421429,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,01
1048349,3421429,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,02
1048363,3421430,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,12
1048365,3421430,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,02
1048389,3421431,20191001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,10
1048395,3421432,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,12
1048397,3421432,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,02
1048402,3421432,20190701,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,07
1048411,3421434,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,12
1048412,3421434,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,01
1048418,3421434,20190701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,07
1048426,3421435,20181101,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,11
1048427,3421435,20181201,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,100.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2018,12
1048451,3421437,20190801,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2019,08
1048459,3421438,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2018,12
1048463,3421438,20190401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,04
1048467,3421438,20190801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,08
1048469,3421438,20191001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,2019,10
1048507,3421441,20181201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,12
1048509,3421441,20190201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,02
1048512,3421441,20190501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2019,05
1048513,3421441,20190601,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,...,100.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2019,06
1048522,2885958,20180501,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,05
1048525,2885958,20180801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018,08
1048531,2885958,20190201,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2019,02
1048574,2885967,20190101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2019,01

In [505]:
#add_groupby_month=df[['VideoAddOrders','InternetAddOrders','PhoneAddOrders','PhoneLinesAdded','year','month']].groupby(['year','month']).sum()
#add_groupby_month['total']=add_groupby_month[['VideoAddOrders','InternetAddOrders','PhoneAddOrders','PhoneLinesAdded']].transform(
#    lambda x: x['VideoAddOrders']+x['InternetAddOrders']+x['PhoneAddOrders']+x['PhoneLinesAdded'])
#add_groupby_month

In [506]:
#def sum_add(x):
#    x['total']=x['VideoAddOrders']+x['InternetAddOrders']
#add_groupby_month['total']=add_groupby_month[['VideoAddOrders','InternetAddOrders']].transform(sum_add)

In [504]:
df_group=df.pivot_table(index=['year','month'],values=['VideoAddOrders','InternetAddOrders','PhoneAddOrders','PhoneLinesAdded'], 
               aggfunc=np.sum, margins=True)
df_group['sum']=df_group['VideoAddOrders']+df_group['InternetAddOrders']+df_group['PhoneAddOrders']+df_group['PhoneLinesAdded']
df_group

#{'VideoAddOrders':np.sum, 'InternetAddOrders':np.sum,'PhoneAddOrders':np.sum,'PhoneLinesAdded':np.sum}

            InternetAddOrders  PhoneAddOrders  PhoneLinesAdded  \
year month
2018 01                 189.0            40.0             40.0
     02                 231.0            31.0             31.0
     03                 208.0            30.0             30.0
     04                 168.0            30.0             31.0
     05                 269.0            27.0             27.0
     06                3098.0           155.0            156.0
     07                6136.0           355.0            357.0
     08                5200.0           350.0            352.0
     09                1871.0           125.0            126.0
     10                1325.0           107.0            107.0
     11                 529.0            46.0             49.0
     12                 267.0            27.0             28.0
2019 01                 358.0            32.0             32.0
     02                 309.0            33.0             33.0
     03                 312.0            33.0             34.0
     04                 337.0            36.0             36.0
     05                 280.0            36.0             38.0
     06                 234.0            18.0             18.0
     07                 266.0            22.0             22.0
     08                 344.0            36.0             36.0
     09                 286.0            24.0             24.0
     10                 233.0            31.0             32.0
All                   22450.0          1624.0           1639.0

            VideoAddOrders      sum
year month
2018 01               75.0    344.0
     02               65.0    358.0
     03               58.0    326.0
     04               72.0    301.0
     05               75.0    398.0
     06              574.0   3983.0
     07              945.0   7793.0
     08             1052.0   6954.0
     09              470.0   2592.0
     10              360.0   1899.0
     11              163.0    787.0
     12               78.0    400.0
2019 01               92.0    514.0
     02               74.0    449.0
     03              100.0    479.0
     04              103.0    512.0
     05               79.0    433.0
     06               71.0    341.0
     07               65.0    375.0
     08              103.0    519.0
     09               92.0    426.0
     10               98.0    394.0
All                 4864.0  30577.0